### ISSUE TITLE
What do you use to migrate databases?

### ISSUE THREAD

**Issue by mitramejia** [anttiviljami/wordpress-heroku-docker-project#4]
What tool do you recommend for this stack

Thank you!

**Comment by anttiviljami** [comment]
Hi, @mitramejia ! 

I'm not using any migration tool since in WordPress philosophy it's the plugins' responsibility to handle all db schema changes, if any.

I'm guessing you need something to move content or configuration (wp_options) between instances?

To move database content between instances, I highly recommend using wp-cli. In a lot of cases, I like to use wp-cli in post-deploy scripts to import content / configuration and then most often applying a search-replace rule. 

Let me know your specific need for migrations and I'll try to help. :)

**Comment by mitramejia** [comment]
Great answer! If you want please share one of those post-deploy scripts, thanks man!

**Comment by mitramejia** [comment]
As a follow up why'd you chose to use AWS to host the database vs using plain old heroku postgres?

**Comment by anttiviljami** [comment]
WordPress doesn’t officially support postgres and a lot of plugins (e.g. for search) directly use MySQL-only features. 

Hope you noticed the wp-cli based migration scripts I added in the tools directory btw! :)
