### ISSUE TITLE
Heroku times out when starting up for the first time

### ISSUE THREAD

**Issue by crwallace** [anttiviljami/wordpress-heroku-docker-project#6]
I keep seeing "Application Error" because the first install of Wordpress takes more than 30s after deployment to Heroku.

![screenshot 2017-08-15 11 22 32](https://user-images.githubusercontent.com/3453669/29322604-1acd461a-81ac-11e7-8ee4-77dd9896df22.png)

**Comment by tsarnow** [comment]
I have exactly the same issue. When it comes to console it says: 
> State changed from up to starting 
Stopping all processes with SIGTERM 
Process exited with status 143 
Going down, terminating child processes... 
Starting process with command `tools/start-web.sh` 
DOCUMENT_ROOT changed to 'htdocs/' 
Using Nginx server-level configuration include 'config/nginx.conf' 
Optimizing defaults for 1X dyno... 
4 processes at 128MB memory limit. 
Starting php-fpm... 
Starting nginx... 

I kinda get the feelin that nginx is not properly configured since I cant even access my docker environment on localhost:8080 - only http://192.168.99.100:8080/ works for me - but I'm still looking around...

**Comment by anttiviljami** [comment]
no other errors in the heroku log?

**Comment by anttiviljami** [comment]
@tsarnow this sounds like your docker setup isn't binding to localhost 127.0.0.1 by default. Can you post more information about your environment?

**Comment by anttiviljami** [comment]
No reply for 30 days, so I'm assuming the original author of this issue resolved their problem. Closing issue now.
